# Generated by Django 2.2.3 on 2019-12-12 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_auto_20191111_1844'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='tariff',
            field=models.ImageField(blank=True, null=True, upload_to='company_tariff/', verbose_name='Cennik'),
        ),
    ]
