# Generated by Django 2.2.3 on 2019-10-09 21:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Advert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, null=True)),
                ('title', models.CharField(max_length=120, verbose_name='Tytuł')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Opis')),
                ('category', models.CharField(choices=[('Dom', 'Dom'), ('Mieszkanie', 'Mieszkanie'), ('Pokój', 'Pokój')], max_length=10, verbose_name='Kategoria')),
                ('advert_type', models.CharField(choices=[('Wynajem', 'Wynajem'), ('Sprzedaż', 'Sprzedaż')], max_length=10, verbose_name='Typ')),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('furnished', models.BooleanField(default=False, verbose_name='Umeblowanie')),
                ('city', models.CharField(max_length=100, verbose_name='Miasto')),
                ('address', models.CharField(max_length=100, verbose_name='Adres')),
                ('price', models.CharField(max_length=10, verbose_name='Cena')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Zdjęcia')),
                ('user', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
