# Generated by Django 2.2.3 on 2019-10-13 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adverts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advert',
            name='price',
            field=models.IntegerField(default=1000, verbose_name='Cena'),
        ),
    ]
