# Generated by Django 2.2.3 on 2019-10-13 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adverts', '0002_auto_20191013_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advert',
            name='price',
            field=models.IntegerField(verbose_name='Cena'),
        ),
    ]
