# Generated by Django 2.2.3 on 2019-10-22 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adverts', '0003_auto_20191013_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advert',
            name='price',
            field=models.PositiveIntegerField(verbose_name='Cena'),
        ),
    ]
