# Generated by Django 2.2.3 on 2019-11-20 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adverts', '0005_auto_20191110_1056'),
    ]

    operations = [
        migrations.AddField(
            model_name='advert',
            name='map_coord_x',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='advert',
            name='map_coord_y',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='advert',
            name='map_url',
            field=models.CharField(default='', max_length=200),
        ),
    ]
