# Generated by Django 2.2.3 on 2019-11-20 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adverts', '0006_auto_20191120_1935'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advert',
            name='map_coord_x',
        ),
        migrations.RemoveField(
            model_name='advert',
            name='map_coord_y',
        ),
        migrations.RemoveField(
            model_name='advert',
            name='map_url',
        ),
    ]
