# Generated by Django 2.2.3 on 2019-09-19 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adverts', '0012_auto_20190919_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='advert',
            name='category',
            field=models.CharField(choices=[('D', 'Dom'), ('M', 'Mieszkanie'), ('P', 'Pokój')], default='Brak', max_length=1),
        ),
    ]
