# Generated by Django 2.2.3 on 2019-09-19 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adverts', '0013_advert_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advert',
            name='category',
            field=models.CharField(choices=[('D', 'Dom'), ('M', 'Mieszkanie'), ('P', 'Pokój')], max_length=1),
        ),
    ]
