# Generated by Django 2.2.3 on 2019-09-19 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adverts', '0019_auto_20190919_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='advert',
            name='advert_type',
            field=models.CharField(choices=[('Wynajem', 'Wynajem'), ('Sprzedaż', 'Sprzedaż')], default='Wynajem', max_length=10),
        ),
    ]
