# Generated by Django 2.2.3 on 2019-09-19 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adverts', '0020_advert_advert_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advert',
            name='advert_type',
            field=models.CharField(choices=[('Wynajem', 'Wynajem'), ('Sprzedaż', 'Sprzedaż')], max_length=10),
        ),
    ]
