# Generated by Django 2.2.3 on 2019-09-20 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adverts', '0021_auto_20190919_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='advert',
            name='furnished',
            field=models.BooleanField(default=False),
        ),
    ]
