# Generated by Django 2.2.3 on 2019-10-09 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adverts', '0022_advert_furnished'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advert',
            name='title',
            field=models.CharField(max_length=120, verbose_name='Tytuł'),
        ),
    ]
