# Generated by Django 2.2.3 on 2019-10-26 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='birth_date',
            field=models.DateField(blank=True, verbose_name='Data urodzenia'),
        ),
    ]
