# Generated by Django 2.2.3 on 2019-10-26 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20191026_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Zdjęcie profilowe'),
        ),
    ]
