# Generated by Django 2.2.3 on 2019-08-16 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adverts', '0003_auto_20190816_1312'),
    ]

    operations = [
        migrations.AddField(
            model_name='advert',
            name='city',
            field=models.CharField(default='none', max_length=100),
        ),
    ]
