# Generated by Django 2.2.3 on 2019-08-16 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adverts', '0004_advert_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advert',
            name='city',
            field=models.CharField(max_length=100),
        ),
    ]
