# Generated by Django 2.2.3 on 2019-09-18 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adverts', '0008_auto_20190817_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='advert',
            name='address',
            field=models.CharField(default='Brak', max_length=100),
        ),
    ]
