# Generated by Django 2.2.3 on 2019-09-18 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adverts', '0009_advert_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advert',
            name='address',
            field=models.CharField(max_length=100),
        ),
    ]
