# Generated by Django 2.2.3 on 2019-08-16 12:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('adverts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='advert',
            name='create_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
