# Generated by Django 2.2.3 on 2019-08-16 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adverts', '0002_advert_create_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advert',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
