# Generated by Django 2.2.3 on 2019-08-16 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adverts', '0005_auto_20190816_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advert',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
