# Generated by Django 2.2.3 on 2019-08-17 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adverts', '0007_advert_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advert',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
